### ISSUE TITLE
沟通适如果没有打开小窗口沟通,而是专门的聊天页列表,程序终止运行.

### ISSUE THREAD

**Issue by gitkakafu** [engvuchen/boss-zhipin-robot-web#10]
3s 内未获取到小窗输入框
3s 内未获取到沟通列表输入框
❌ 执行出错 TypeError: Cannot read properties of undefined (reading 'type')

**Comment by engvuchen** [comment]
一开始投递数量比较少，是小窗；
投递数量比较多之后，是聊天页；
2种都支持的，试试增大“超时时间”，页面里面就有设置

**Comment by engvuchen** [comment]
也可能是触发到BOSS安全检测了，需要手动在网页端验证
![653e387c03852d244445b35bb74042d2](https://github.com/engvuchen/boss-zhipin-robot-web/assets/31369318/49aa0358-c228-47fa-9e6e-7453c8991d67)
