### ISSUE TITLE
沟通过的boss在app上无法显示

### ISSUE THREAD

**Issue by thisisWuRan** [engvuchen/boss-zhipin-robot-web#11]
沟通过的boss在app上和网页的消息窗口内无法显示，并不清楚到底是有没有真正沟通过，沟通的boss到底是哪几位。并且无法自动翻页

**Comment by engvuchen** [comment]
1. 项目运行应该是失败了，辛苦发下运行截图（整图）
2. 可以关注下日志消息，看看是不是被 BOSS 拦截了
