### ISSUE TITLE
项目初始化出错

### ISSUE THREAD

**Issue by Erional** [engvuchen/boss-zhipin-robot-web#13]
npm:9.71 nodejs:16.18.1
<img width="960" alt="PixPin_2024-06-11_15-35-29" src="https://github.com/engvuchen/boss-zhipin-robot-web/assets/105800742/27b40670-95ab-4aa4-9075-f77ab44e80b9">

**Comment by engvuchen** [comment]
> npm:9.71 nodejs:16.18.1 <img alt="PixPin_2024-06-11_15-35-29" width="960" src="https://private-user-images.githubusercontent.com/105800742/338484058-27b40670-95ab-4aa4-9075-f77ab44e80b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTMzMjIsIm5iZiI6MTcxODA5MzAyMiwicGF0aCI6Ii8xMDU4MDA3NDIvMzM4NDg0MDU4LTI3YjQwNjcwLTk1YWItNGFhNC05MDc1LWY3N2FiNDRlODBiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwODAzNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzhmYjg2YzJiYmE0OTU1OWE5YjAyNTI1OTdiOWM1YmQxNDllMTlkMWY1Nzc5ODE1NzZkNzlhZGIwZTAxM2E5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XyCOheGzmNtLNubpIbNL6ITlXLcntaL7IOBmapPDsPA">

终端是 bash 吗？&& 没生效，npm i 没跑完，node app.js 就执行了；也可以先 npm i，后 node app.js

**Comment by Erional** [comment]
1. 使用git自带的bash终端
2. 先执行npm i安装成功
3. 执行npm run dev或node app.js出现相同报错

**Comment by engvuchen** [comment]
> 1. 使用git自带的bash终端
> 2. 先执行npm i安装成功
> 3. 执行npm run dev或node app.js出现相同报错

boss-zhipin-robot-core 是必须的，发的时候忘记还原了，git pull 拉下最新修改，npm i 之后可以再试下

**Comment by engvuchen** [comment]
> 1. 使用git自带的bash终端
> 2. 先执行npm i安装成功
> 3. 执行npm run dev或node app.js出现相同报错

应该OK了吧？关ISSUE了
