### ISSUE TITLE
执行npm run init-dev页面空白，console报错

### ISSUE THREAD

**Issue by YDBZS** [engvuchen/boss-zhipin-robot-web#15]
<img width="1763" alt="image" src="https://github.com/engvuchen/boss-zhipin-robot-web/assets/38450935/023ac3db-967c-4f0a-87d7-9098be65f8a0">
并且BOSS页面也修改成自己的了。
<img width="1764" alt="image" src="https://github.com/engvuchen/boss-zhipin-robot-web/assets/38450935/4041dcac-db37-4b46-8404-a5c5cc72242f">

**Comment by engvuchen** [comment]
修复在main分支，可以再试下

**Comment by YDBZS** [comment]
感谢大佬的开源，这边有一个请求，我这边是在两个平台投递两个城市(BOSS直聘以及智联招聘)，大佬能否适配一下智联招聘。。。感谢

**Comment by engvuchen** [comment]
精力有限，暂时不考虑适配其他平台
