### ISSUE TITLE
解决下报错

### ISSUE THREAD

**Issue by jack-hub-maker** [engvuchen/boss-zhipin-robot-web#2]
file: index.js:51 ~ error: Error: Error: failed to find element matching selector "div.chat-conversation > div.message-controls > div > div.chat-input"

**Comment by engvuchen** [comment]
可以更新 boss-zhipin-robot-core 到 0.0.5 版本，兼容了点击“立即沟通”出现小窗、沟通列表

**Comment by engvuchen** [comment]
选择器问题可以拉下 `main` 分支最新修改，已经修复了
