### ISSUE TITLE
似乎招呼语没效果，只会发您好？

### ISSUE THREAD

**Issue by jack-hub-maker** [engvuchen/boss-zhipin-robot-web#3]

**Comment by engvuchen** [comment]
“您好”是固定招呼语，自定义招呼语没有被正确填入输入框；尝试更新 boss-zhipin-robot-core 到 0.0.5 版本

**Comment by baoqihui** [comment]
我这边测试是只打开对话框，不会发送我们的招呼语，但boss-zhipin-robot-core 是 0.0.5

**Comment by engvuchen** [comment]
> 我这边测试是只打开对话框，不会发送我们的招呼语，但boss-zhipin-robot-core 是 0.0.5

可以加群投屏看下

<img width="668" alt="image" src="https://github.com/engvuchen/boss-zhipin-robot-web/assets/31369318/732448c9-186f-409f-9552-d1a351308bf2">

**Comment by engvuchen** [comment]
初步推定BOSS返回资源超过1秒，选择器获取元素失败；
这个问题发生还挺随机的，群友反馈又没这个问题了
