### ISSUE TITLE
运行之后不久会出现这个错误：~ file: index.js:51 ~ error: TypeError: Cannot read properties of null (reading 'type')

### ISSUE THREAD

**Issue by javarike** [engvuchen/boss-zhipin-robot-web#6]
运行之后不久会出现这个错误：~ file: index.js:51 ~ error: TypeError: Cannot read properties of null (reading 'type')

mac电脑，chrome浏览器。

必现。

**Comment by engvuchen** [comment]
> 运行之后不久会出现这个错误：~ file: index.js:51 ~ error: TypeError: Cannot read properties of null (reading 'type')
> 
> mac电脑，chrome浏览器。
> 
> 必现。

加群投屏看看
![image](https://github.com/engvuchen/boss-zhipin-robot-web/assets/31369318/e95e77ca-cfe1-4855-b471-ed1bce72f4fa)

**Comment by engvuchen** [comment]
已解决

**Comment by engvuchen** [comment]
> 运行之后不久会出现这个错误：~ file: index.js:51 ~ error: TypeError: Cannot read properties of null (reading 'type')
> 
> mac电脑，chrome浏览器。
> 
> 必现。

已解决
