### ISSUE TITLE
重复沟通的话，有问题，不会跳过。

### ISSUE THREAD

**Issue by 1450687719** [engvuchen/boss-zhipin-robot-web#7]
❌ 执行出错 Error: Error: failed to find element matching selector "a.start-chat-btn"

**Comment by engvuchen** [comment]
> ❌ 执行出错 Error: Error: failed to find element matching selector "a.start-chat-btn"

修改超时时间可以吗？

或者加群投屏看下？

<img width="205" alt="image" src="https://github.com/engvuchen/boss-zhipin-robot-web/assets/31369318/73ae870a-1689-47e3-9357-0f420fac56cc">

**Comment by 1450687719** [comment]
这一段代码有问题，如果是已沟通，找不到这个a.start-chat-btn属性，改成这样我就解决了。
`async function autoSayHello(marketPage) {
  await marketPage.waitForSelector('li.job-card-wrapper').catch(e => {
    throw new Error('3s 内未获取岗位列表');
  });
  let jobCards = Array.from(await marketPage.$$('li.job-card-wrapper'));
  if (!jobCards?.length) {
    throw new Error('岗位列表为空');
  }
  let notPostJobs = await asyncFilter(jobCards, async node => {
    let notCommunicate
    try {
       notCommunicate = (await node.$eval('a.start-chat-btn', node => node.innerText)) !== '继续沟通'; // 岗位卡片存在，是否沟通的文案
    }catch (e){
      return false;
    }`

**Comment by shawwahweng** [comment]
> > ❌ 执行出错 Error: Error: failed to find element matching selector "a.start-chat-btn"
> 
> 修改超时时间可以吗？
> 
> 或者加群投屏看下？
> 
> <img alt="image" width="205" src="https://private-user-images.githubusercontent.com/31369318/273436606-73ae870a-1689-47e3-9357-0f420fac56cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTcwMjAsIm5iZiI6MTcwODkxNjcyMCwicGF0aCI6Ii8zMTM2OTMxOC8yNzM0MzY2MDYtNzNhZTg3MGEtMTY4OS00N2UzLTkzNTctMGY0MjBmYWM1NmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAzMDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YjAyN2UxNjBkMzE1NmIzMDg3ODZmYzRlYWYyYzg2NWUzMmIzNWVkODhlNTE5M2Q2YzFiYTZkMTc2YTZkMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vLl0ySSWkdE4zyTbtKdo3vc69roENYJBXrb217_-9VQ">

驗證碼過期

**Comment by engvuchen** [comment]
> > > ❌ 执行出错 Error: Error: failed to find element matching selector "a.start-chat-btn"
> > 
> > 
> > 修改超时时间可以吗？
> > 或者加群投屏看下？
> > <img alt="image" width="205" src="https://private-user-images.githubusercontent.com/31369318/273436606-73ae870a-1689-47e3-9357-0f420fac56cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTcwMjAsIm5iZiI6MTcwODkxNjcyMCwicGF0aCI6Ii8zMTM2OTMxOC8yNzM0MzY2MDYtNzNhZTg3MGEtMTY4OS00N2UzLTkzNTctMGY0MjBmYWM1NmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAzMDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YjAyN2UxNjBkMzE1NmIzMDg3ODZmYzRlYWYyYzg2NWUzMmIzNWVkODhlNTE5M2Q2YzFiYTZkMTc2YTZkMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vLl0ySSWkdE4zyTbtKdo3vc69roENYJBXrb217_-9VQ">
> 
> 驗證碼過期

是遇到相同的问题？

**Comment by Erional** [comment]
建议将KeySkills改为非必填项。或者可以自填而不是仅能选择下拉框中的技能
