### ISSUE TITLE
无法自动点击立即沟通

### ISSUE THREAD

**Issue by SerMs** [engvuchen/boss-zhipin-robot-web#8]
筛选成功搜索到合适的公司及岗位，点击立即沟通，Boss会弹出对话框，程序无法自动点击继续沟通
![image](https://github.com/engvuchen/boss-zhipin-robot-web/assets/67584847/ebe4dd89-f852-475b-83e5-ec18546850d8)
![image](https://github.com/engvuchen/boss-zhipin-robot-web/assets/67584847/7a8810a0-33a1-4840-83c1-e28b25036e09)

![image](https://github.com/engvuchen/boss-zhipin-robot-web/assets/67584847/40da1db6-14e5-4bbb-8b5f-22b0b4dac8d2)

**Comment by engvuchen** [comment]
不要启用默认的招呼语，目前没有程序没有覆盖有默认招呼语的情况；
自定义招呼语会好一点，没有做默认招呼语的逻辑。

![image](https://github.com/engvuchen/boss-zhipin-robot-web/assets/31369318/9b1b5a62-24e2-47b1-b602-d42dbd41ffc3)

<img width="262" alt="image" src="https://github.com/engvuchen/boss-zhipin-robot-web/assets/31369318/21a01b57-2cc8-4827-842f-c98210986477">

<img width="725" alt="image" src="https://github.com/engvuchen/boss-zhipin-robot-web/assets/31369318/acbb2bb0-2ce4-4504-b213-5e2738ea093d">

**Comment by SerMs** [comment]
好的好的，谢谢
我还有一个疑问，按照查询出来的之后，是不是从最后一页开始进行逐一的筛选职位？
我运行之后观察了一阵子，搜索出来加入第一页第一个，是A公司，往下就是B、C、D....，但是我发现他好像并不是按照这个规律来的，反而有点像是从最后一页开始的，越往后搜索出来的内容就越不符合个人要求，看是否能从第一页往后进行呢？

**Comment by SerMs** [comment]
还有就是，筛选的是Javak开发
[查询链接为](https://www.zhipin.com/web/geek/job?query=java%E5%BC%80%E5%8F%91&city=101250100&degree=202&scale=302&salary=404&areaBusiness=430102,430121)
为啥他还会搜到React的岗位进行打招呼呢？
![image](https://github.com/engvuchen/boss-zhipin-robot-web/assets/67584847/c3da998a-dae4-46e3-b28e-cfc1d5445cdd)
![image](https://github.com/engvuchen/boss-zhipin-robot-web/assets/67584847/0b146d77-6ddf-4881-90ed-9c0338e759bb)

**Comment by SerMs** [comment]
![image](https://github.com/engvuchen/boss-zhipin-robot-web/assets/67584847/74ac1967-7e7b-4901-b05a-3532c57b6754)

**Comment by engvuchen** [comment]
1. 就是从第一页开始的；
2. 看你的截图，只有 1 页；我晚点跑一下看看是不是页码的选择器改了；
3. “精确匹配”是工作要求包含。那个工作岗位是既包含“java”，也包括“react”了；
4. 新加的词可能没有 lowercase，晚点我一起看下

**Comment by engvuchen** [comment]
方便的话，可以加群沟通：
<img width="147" alt="image" src="https://github.com/engvuchen/boss-zhipin-robot-web/assets/31369318/3e9d5f60-b61c-44da-aae5-67eb5d80dfb6">

**Comment by SerMs** [comment]
好的，谢谢

**Comment by engvuchen** [comment]
已解决
