### ISSUE TITLE
advise

### ISSUE THREAD

**Issue by Erional** [engvuchen/boss-zhipin-robot-web#9]
建议将**KeySkills**改为非必填项。或者可以自填而不是仅能选择下拉框中的技能。

**Comment by engvuchen** [comment]
可以自由编辑的，在最后一个项后面输入文字，然后按下 enter，就可以生成一个新的项
https://www.naiveui.com/zh-CN/os-theme/components/select
<img width="1034" alt="2024-03-13 145455" src="https://github.com/engvuchen/boss-zhipin-robot-web/assets/31369318/e19f7d89-161e-47fb-b7b3-32681dae0181">

**Comment by engvuchen** [comment]
已回复，未反馈，先关了，有问题可以再打开
